services:
  postgres:
    container_name: postgres-sql-nexus-chat
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: atekur
      POSTGRES_DB: nexus_chat_db
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - nexus-chat
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped

  keycloak:
    container_name: keycloak-nexus-chat
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - 8585:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - nexus-chat
    volumes:
      - keycloak:/data/keycloak
    command:
      - "start-dev"

networks:
  nexus-chat:
    driver: bridge
volumes:
  postgres:
    driver: local
  keycloak:
    driver: local

